require "core.options"
require "core.keymaps"
require "core.autocmds"
require "core.plugins"
require "core.lsp"
require "core.treesitter"

require "config.colorscheme"
require "config.cmp"
require "config.telescope"
require "config.colorizer"
require "config.autopairs"
require "config.gitsigns"
require "config.nvim-tree"
